"""
api/str_generator.py
Auto-generate a Suspicious Transaction Report (STR) per detected ring.

Output simulates the FIU-IND STR structure for demonstration.
NOT legally compliant with actual RBI/FIU-IND requirements.
"""

from __future__ import annotations

import uuid
from datetime import datetime


def generate_str(ring: dict) -> str:
    case_id    = f"STR-{ring['ring_id']}-{uuid.uuid4().hex[:6].upper()}"
    generated  = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    patterns   = ", ".join(ring.get("patterns", [])) or "None detected"
    members    = "\n    ".join(ring.get("members", []))

    return f"""
╔══════════════════════════════════════════════════════════════╗
║       SUSPICIOUS TRANSACTION REPORT (STR) — SIMULATION      ║
║       FIU-IND Format · For Demonstration Only                ║
╚══════════════════════════════════════════════════════════════╝

Case ID         : {case_id}
Ring ID         : {ring['ring_id']}
Generated       : {generated}

━━━ RING SUMMARY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Flagged Accounts   : {ring['node_count']}
Total Amount (USD) : {ring['total_amount']:,.2f}
Time Window        : {ring.get('time_window', 'N/A')}
Active Patterns    : {patterns}

━━━ MASTERMIND ACCOUNT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Account ID         : {ring['mastermind']}
Mastermind Score   : {ring['mastermind_score']:.4f}
  (composite: 0.5 × PageRank + 0.5 × Betweenness Centrality)

━━━ FLAGGED ACCOUNTS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    {members}

━━━ PATTERN DETAIL ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{"  ● Circular Fund Flow       — Round-trip transactions detected (3–4 hop cycles)" if "Circular Fund Flow" in ring.get("patterns", []) else ""}
{"  ● Mule Account Network     — Fan-in > 5 unique senders detected" if "Mule Account Network" in ring.get("patterns", []) else ""}
{"  ● Currency Layering        — Cross-currency transactions within cluster" if "Currency Layering" in ring.get("patterns", []) else ""}
{"  ● Dormant Activation       — >10 transactions in 2-day window" if "Dormant Activation" in ring.get("patterns", []) else ""}

━━━ DISCLAIMER ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This STR is a simulation generated by SecureLedger for the
PSBs Hackathon 2026 (iDEA 2.0). It is NOT legally compliant
with actual RBI/FIU-IND submission requirements, which mandate
digital signatures and a specific XML schema.

All account IDs are SHA-256 anonymised. Dataset: IBM AML
(CDLA-Sharing-1.0). No real customer data is used.
""".strip()
